use anyhow::{anyhow, Context, Result};
use std::path::Path;

use crate::config::Config;
use crate::git;
use crate::state::InkState;

// ─── Constants ─────────────────────────────────────────────────────────────────

pub(crate) const FULL_BOOK_HEADER: &str =
    "<!-- ⚠ INK-GATEWAY:MANAGED — Do not edit this file directly.\n\
     Human edits belong in Review/current.md.\n\
     Validated content is appended automatically after each session.\n\
     Use `ink-cli rollback` to undo the last session. -->";

// ─── Prose utilities ───────────────────────────────────────────────────────────

/// Strip engine-generated INK markers from prose before it enters Full_Book.md.
/// Per spec, `<!-- INK:NEW:START/END -->` and `<!-- INK:REWORKED:START/END -->` markers
/// live only in `current.md` and must never appear in the validated vault.
pub(crate) fn strip_engine_markers(text: &str) -> String {
    text.lines()
        .filter(|l| {
            let t = l.trim();
            !matches!(
                t,
                "<!-- INK:NEW:START -->"
                    | "<!-- INK:NEW:END -->"
                    | "<!-- INK:REWORKED:START -->"
                    | "<!-- INK:REWORKED:END -->"
            ) && !t.starts_with("> **[Rework]**")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Count prose words, ignoring HTML comment lines (e.g. `<!-- PAGE N -->`).
/// Used by both session-close (maintenance) and session-open word_count (context)
/// so both always report the same figure.
pub fn count_prose_words(content: &str) -> u32 {
    content
        .lines()
        .filter(|l| !l.trim_start().starts_with("<!--"))
        .flat_map(|l| l.split_whitespace())
        .count() as u32
}

// ─── Pagination ────────────────────────────────────────────────────────────────

/// Insert `<!-- PAGE N -->` markers into `new_content` at paragraph boundaries
/// closest to each `words_per_page` boundary, given that the book already has
/// `start_word_count` prose words before this content.
fn insert_pagination(start_word_count: u32, new_content: &str, words_per_page: u32) -> String {
    if words_per_page == 0 {
        return new_content.to_string();
    }

    let mut chunks: Vec<String> = Vec::new();
    let mut cumulative = start_word_count;
    // First boundary we haven't yet marked.
    // When start_word_count is an exact multiple, the new content opens a new page
    // immediately — so next_mark equals start_word_count (but never 0).
    let mut next_mark = if start_word_count > 0 && start_word_count.is_multiple_of(words_per_page) {
        start_word_count
    } else {
        ((start_word_count / words_per_page) + 1) * words_per_page
    };

    for para in new_content.split("\n\n") {
        let para = para.trim();
        if para.is_empty() {
            continue;
        }
        let para_words = para.split_whitespace().count() as u32;

        // Insert marker(s) for every boundary this paragraph starts at, crosses, or lands on
        while cumulative <= next_mark && cumulative + para_words >= next_mark {
            let page_num = next_mark / words_per_page + 1;
            chunks.push(format!("<!-- PAGE {} -->", page_num));
            next_mark += words_per_page;
        }

        chunks.push(para.to_string());
        cumulative += para_words;
    }

    chunks.join("\n\n")
}

// ─── Full_Book.md I/O ──────────────────────────────────────────────────────────

/// Append `content` to `Full_Book.md` at `book_path` with pagination markers.
/// Creates the file (with managed header) if it doesn't exist.
/// Returns `(old_word_count, new_word_count)` — both computed in a single read,
/// so callers don't need a separate pre-read to calculate words_added.
pub(crate) fn append_to_full_book(
    book_path: &Path,
    content: &str,
    words_per_page: u32,
) -> Result<(u32, u32)> {
    let mut book = if book_path.exists() {
        std::fs::read_to_string(book_path).with_context(|| "Failed to read Full_Book.md")?
    } else {
        format!("{}\n", FULL_BOOK_HEADER)
    };

    let old_words = count_prose_words(&book);
    let paginated = insert_pagination(old_words, content.trim(), words_per_page);

    if !book.ends_with('\n') {
        book.push('\n');
    }
    book.push('\n');
    book.push_str(&paginated);
    if !book.ends_with('\n') {
        book.push('\n');
    }

    let new_words = count_prose_words(&book);
    std::fs::write(book_path, &book).with_context(|| "Failed to write Full_Book.md")?;
    Ok((old_words, new_words))
}

// ─── Format check ──────────────────────────────────────────────────────────────

/// Scan `Full_Book.md` for structural issues without loading full prose into context.
/// Returns `None` if the book passes all checks, or `Some(needs_formatting JSON)` if issues found.
pub(crate) fn check_full_book_format(repo: &Path) -> Result<Option<serde_json::Value>> {
    let book_path = repo.join("Current version").join("Full_Book.md");

    // Nothing to check if Full_Book.md doesn't exist yet
    if !book_path.exists() {
        return Ok(None);
    }

    let config = Config::load(repo)?;
    let state = InkState::load(repo).unwrap_or_default();

    let content = std::fs::read_to_string(&book_path)
        .with_context(|| "Failed to read Full_Book.md for format check")?;

    let mut format_issues: Vec<&'static str> = Vec::new();

    // ── Check 1: managed header ───────────────────────────────────────────────
    let first_nonempty = content.lines().find(|l| !l.trim().is_empty());
    let has_managed_header = first_nonempty
        .map(|l| l.trim_start().starts_with("<!--"))
        .unwrap_or(false);
    if !has_managed_header {
        format_issues.push("missing_managed_header");
    }

    // ── Scan lines: build sections skeleton + collect page markers ────────────
    let mut sections: Vec<serde_json::Value> = Vec::new();
    let mut heading_count: u32 = 0;
    let mut page_numbers: Vec<u32> = Vec::new();

    let mut cur_heading: Option<String> = None;
    let mut cur_first_line: Option<String> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        // PAGE marker: <!-- PAGE N -->
        if trimmed.starts_with("<!-- PAGE ") && trimmed.ends_with(" -->") {
            let inner = &trimmed["<!-- PAGE ".len()..trimmed.len() - " -->".len()];
            if let Ok(n) = inner.trim().parse::<u32>() {
                page_numbers.push(n);
            }
            continue;
        }

        // Heading: start a new section
        if trimmed.starts_with("# ") || trimmed.starts_with("## ") {
            // Flush the current section (only if it has content)
            if cur_heading.is_some() || cur_first_line.is_some() {
                sections.push(serde_json::json!({
                    "heading": cur_heading,
                    "first_line": cur_first_line,
                }));
            }
            cur_heading = Some(trimmed.to_string());
            cur_first_line = None;
            heading_count += 1;
            continue;
        }

        // First prose line of this section (skip blanks and HTML comments)
        if cur_first_line.is_none() && !trimmed.is_empty() && !trimmed.starts_with("<!--") {
            let s = if trimmed.len() > 200 {
                &trimmed[..200]
            } else {
                trimmed
            };
            cur_first_line = Some(s.to_string());
        }
    }

    // Flush the final pending section
    if cur_heading.is_some() || cur_first_line.is_some() {
        sections.push(serde_json::json!({
            "heading": cur_heading,
            "first_line": cur_first_line,
        }));
    }

    // ── Check 2: no headings at all ───────────────────────────────────────────
    if heading_count == 0 {
        format_issues.push("no_headings");
    }

    // ── Check 3: page markers sequential (only when pagination is active) ─────
    let page_count = page_numbers.len() as u32;
    let pages_sequential = page_numbers.is_empty()
        || (page_numbers[0] == 1 && page_numbers.windows(2).all(|w| w[1] == w[0] + 1));

    if config.words_per_page > 0 && !page_numbers.is_empty() && !pages_sequential {
        format_issues.push("page_markers_not_sequential");
    }

    let total_word_count = count_prose_words(&content);

    let skeleton = serde_json::json!({
        "has_managed_header": has_managed_header,
        "sections": sections,
        "heading_count": heading_count,
        "chapters_expected": config.chapter_count,
        "current_chapter": state.current_chapter,
        "page_markers": {
            "count": page_count,
            "sequential": pages_sequential,
        },
        "total_word_count": total_word_count,
    });

    if format_issues.is_empty() {
        Ok(None)
    } else {
        Ok(Some(serde_json::json!({
            "status": "needs_formatting",
            "format_issues": format_issues,
            "book_skeleton": skeleton,
        })))
    }
}

// ─── apply-format ──────────────────────────────────────────────────────────────

/// Apply structural format patches to `Full_Book.md`:
/// - `prepend`: text inserted after the managed-file header comment
/// - `insert_headings`: each entry `{ before_anchor, heading }` inserts a heading line
///   before the first line containing `before_anchor` as a substring
///
/// Commits and pushes `Full_Book.md` on success.
pub fn apply_format_patch(repo: &Path, patch: serde_json::Value) -> Result<serde_json::Value> {
    // Guard: cannot patch a sealed book
    if repo.join("COMPLETE").exists() {
        return Err(anyhow!(
            "book already complete — format patches cannot be applied after sealing"
        ));
    }

    let book_path = repo.join("Current version").join("Full_Book.md");
    if !book_path.exists() {
        return Err(anyhow!("Full_Book.md does not exist — nothing to patch"));
    }

    let mut content = std::fs::read_to_string(&book_path)
        .with_context(|| "Failed to read Full_Book.md for format patch")?;

    let mut patches_applied: u32 = 0;
    let mut warnings: Vec<String> = Vec::new();

    // ── Apply prepend ─────────────────────────────────────────────────────────
    if let Some(prepend) = patch.get("prepend").and_then(|v| v.as_str()) {
        if !prepend.is_empty() {
            // Find the end of the first `-->` (managed-file header closing tag)
            let after_header = content
                .find("-->")
                .map(|pos| pos + "-->".len())
                .unwrap_or(0);
            // Skip one trailing newline if present so our insertion follows naturally
            let insert_pos = if content[after_header..].starts_with('\n') {
                after_header + 1
            } else {
                after_header
            };
            content.insert_str(insert_pos, &format!("\n{}", prepend));
            patches_applied += 1;
        }
    }

    // ── Apply insert_headings ─────────────────────────────────────────────────
    if let Some(inserts) = patch.get("insert_headings").and_then(|v| v.as_array()) {
        for entry in inserts {
            let before_anchor = match entry.get("before_anchor").and_then(|v| v.as_str()) {
                Some(s) if !s.is_empty() => s,
                _ => {
                    warnings.push("insert_headings entry missing 'before_anchor'".to_string());
                    continue;
                }
            };
            let heading = match entry.get("heading").and_then(|v| v.as_str()) {
                Some(s) if !s.is_empty() => s,
                _ => {
                    warnings.push("insert_headings entry missing 'heading'".to_string());
                    continue;
                }
            };

            // Find the byte position of the anchor, then walk back to the line start
            if let Some(anchor_pos) = content.find(before_anchor) {
                let line_start = content[..anchor_pos]
                    .rfind('\n')
                    .map(|i| i + 1)
                    .unwrap_or(0);
                let heading_with_nl = if heading.ends_with('\n') {
                    heading.to_string()
                } else {
                    format!("{}\n\n", heading)
                };
                content.insert_str(line_start, &heading_with_nl);
                patches_applied += 1;
            } else {
                warnings.push(format!("before_anchor not found: '{before_anchor}'"));
            }
        }
    }

    // Write the modified file
    std::fs::write(&book_path, &content).with_context(|| "Failed to write patched Full_Book.md")?;

    // Commit and push
    git::run_git(repo, &["add", "Current version/Full_Book.md"])
        .with_context(|| "Failed to git add Full_Book.md")?;
    git::run_git(repo, &["commit", "-m", "fmt: apply format corrections"])
        .with_context(|| "Failed to commit format corrections")?;
    git::run_git(repo, &["push", "origin", "main"])
        .with_context(|| "Failed to push format corrections")?;

    Ok(serde_json::json!({
        "status": "applied",
        "patches_applied": patches_applied,
        "warnings": warnings,
    }))
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn count_words_ignores_html_comment_lines() {
        let content = "Hello world\n<!-- PAGE 1 -->\nFoo bar baz";
        assert_eq!(count_prose_words(content), 5);
    }

    #[test]
    fn count_words_empty_input() {
        assert_eq!(count_prose_words(""), 0);
    }

    #[test]
    fn strip_engine_markers_removes_start_end_lines() {
        let content = "Before\n<!-- INK:NEW:START -->\nNew prose\n<!-- INK:NEW:END -->\nAfter";
        let stripped = strip_engine_markers(content);
        assert!(!stripped.contains("<!-- INK:NEW:START -->"));
        assert!(!stripped.contains("<!-- INK:NEW:END -->"));
        assert!(stripped.contains("New prose"));
        assert!(stripped.contains("Before"));
        assert!(stripped.contains("After"));
    }

    #[test]
    fn strip_engine_markers_handles_reworked() {
        let content = "A\n<!-- INK:REWORKED:START -->\nB\n<!-- INK:REWORKED:END -->\nC";
        let stripped = strip_engine_markers(content);
        assert!(!stripped.contains("INK:REWORKED"));
        assert!(stripped.contains('B'));
    }

    #[test]
    fn strip_engine_markers_strips_rework_annotation() {
        let input = "<!-- INK:REWORKED:START -->\n> **[Rework]** *Fix pacing*\n\nNew prose.\n\n<!-- INK:REWORKED:END -->";
        let result = strip_engine_markers(input);
        assert!(!result.contains("<!-- INK:REWORKED:START -->"));
        assert!(!result.contains("> **[Rework]**"));
        assert!(result.contains("New prose."));
    }

    #[test]
    fn pagination_inserts_marker_at_boundary() {
        // Build a single paragraph of 300 words; with words_per_page=250 and
        // start_word_count=0 there should be a PAGE 2 marker inserted.
        let para = "word ".repeat(300);
        let result = insert_pagination(0, para.trim(), 250);
        assert!(
            result.contains("<!-- PAGE 2 -->"),
            "expected PAGE 2 in: {result}"
        );
    }

    #[test]
    fn pagination_disabled_when_words_per_page_is_zero() {
        let content = "Some content here";
        let result = insert_pagination(0, content, 0);
        assert_eq!(result, content);
    }

    #[test]
    fn pagination_respects_existing_word_count() {
        // Already at 240 words; next page boundary is 250. A 20-word paragraph
        // should trigger a marker.
        let para = "word ".repeat(20);
        let result = insert_pagination(240, para.trim(), 250);
        assert!(
            result.contains("<!-- PAGE 2 -->"),
            "expected PAGE 2 in: {result}"
        );
    }

    #[test]
    fn pagination_starts_at_exact_boundary() {
        // Already at 500 words (exactly 2 pages). New content should open page 3.
        let para = "word ".repeat(20);
        let result = insert_pagination(500, para.trim(), 250);
        assert!(
            result.contains("<!-- PAGE 3 -->"),
            "expected PAGE 3 in: {result}"
        );
    }

    fn write_test_config(dir: &std::path::Path, words_per_chapter: u32) {
        let global_dir = dir.join("Global Material");
        std::fs::create_dir_all(&global_dir).unwrap();
        let content = format!(
            "target_length: 80000\nchapter_count: 10\nchapter_structure: three-act\n\
             words_per_session: 800\nwords_per_chapter: {}\n",
            words_per_chapter
        );
        std::fs::write(global_dir.join("Config.yml"), content).unwrap();
    }

    fn write_test_state(dir: &std::path::Path, chapter: u32, word_count: u32) {
        let content = format!(
            "current_chapter: {}\ncurrent_chapter_word_count: {}\n",
            chapter, word_count
        );
        std::fs::write(dir.join(".ink-state.yml"), content).unwrap();
    }

    #[test]
    fn format_check_detects_missing_header() {
        let tmp = tempfile::tempdir().unwrap();
        write_test_config(tmp.path(), 3000);
        write_test_state(tmp.path(), 1, 0);

        let book_dir = tmp.path().join("Current version");
        std::fs::create_dir_all(&book_dir).unwrap();
        // No managed header — starts directly with a heading
        std::fs::write(
            book_dir.join("Full_Book.md"),
            "# Chapter One\n\nSome prose here.\n",
        )
        .unwrap();

        let result = check_full_book_format(tmp.path()).unwrap();
        let json = result.expect("should return format issues");
        let issues = json["format_issues"].as_array().unwrap();
        assert!(
            issues
                .iter()
                .any(|v| v.as_str() == Some("missing_managed_header")),
            "expected missing_managed_header in format_issues: {issues:?}"
        );
    }

    #[test]
    fn format_check_clean_book_returns_none() {
        let tmp = tempfile::tempdir().unwrap();
        write_test_config(tmp.path(), 3000);
        write_test_state(tmp.path(), 1, 0);

        let book_dir = tmp.path().join("Current version");
        std::fs::create_dir_all(&book_dir).unwrap();
        let content = concat!(
            "<!-- ⚠ INK-GATEWAY:MANAGED — Do not edit this file directly. -->\n\n",
            "# Book Title\n\n",
            "Some prose here.\n"
        );
        std::fs::write(book_dir.join("Full_Book.md"), content).unwrap();

        let result = check_full_book_format(tmp.path()).unwrap();
        assert!(result.is_none(), "clean book should return None");
    }
}
